import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-black w-screen h-screen flex items-center justify-center p-10'>
        <main className='border border-white w-full h-full bg-default bg-contain'>
          {children}
        </main>
        </body>
    </html>
  )
}
