import type { Metadata } from "next";
import "./globals.css";
import { IBM_Plex_Mono } from "next/font/google";

import Rotated from "@/components/Rotated";
import LanguageSelector from "@/components/LanguageSelector";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const IBMPlexMono = IBM_Plex_Mono({
  weight: ["200", "100", "300", "400", "500", "600", "700"],
  display: "swap",
  style: ["italic", "normal"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={IBMPlexMono.className}>
      <body className="relative bg-black w-screen h-screen flex items-center justify-center p-10">
        <div className="absolute text-white h-screen left-0 w-10 py-10 flex flex-col">
          {/* <LanguageSelector /> */}
          <Rotated className="flex items-center mt-auto text-sm">
            © / 2023
          </Rotated>
        </div>
        <main className="border border-white w-full h-full bg-default bg-contain">
          {children}
        </main>
      </body>
    </html>
  );
}
